### ISSUE TITLE
The Name of the theme is not displayed below the preview in kcm_sddm

### ISSUE THREAD

**Issue by hhl** [siduction/sddm-theme-deepspace#5]
I don't know why, but the name is not displayed in kcm_sddm, see screenshot
http://paste.siduction.org/20160831071513.jpg

Only `@DISPLAY_NAME@` is shown!

There must be something tiny wrong in the funktion.sh file or is there a make file?

Maybe change it to `@CODENAME_SAFE@` ?

**Comment by hhl** [comment]
[bootstrap](https://github.com/siduction/sddm-theme-deepspace/blob/master/template/bootstrap) is the one i think to look for

``` text
sed -e "s#\@CODENAME_SAFE\@#${CODENAME_SAFE}#g" \
    -e "s#\@PREVIEW\@#${PREVIEW}#g" \
    ../template/theme/metadata.desktop \
    > ${CODENAME_SAFE}/metadata.desktop



```

**Comment by agaida** [comment]
und das näxte mal erzählen wir der Welt noch in welchem Theme wir den Mist finden. Danke.

**Comment by hhl** [comment]
@agaida 
Mh, ich hätte schreiben sollen, dass es **alle** Themes betrifft, sorry.

Leider existiert der bug immer noch.

Metadata.desktop wird nicht vollständig generiert.

Hier z.B. die ersten Zeilen der Metadata.desktop vom Theme patience (so wie diese nach Installation auf dem Rechner in /usr/share/sddm/theme/<theme-siduction> landet)

``` bash
[SddmGreeterTheme]
Name=patience
Description=@DISPLAY_NAME@ sddm theme, based on elarun SddmGreeterTheme.`
```

Ich glaube es liegt an bootstrap und einem fehlenden Verweis auf `@DISPLAY_NAME@`.

Ich bin kein sed spezi, aber ich vermute in template/bootstrap ab Zeile 58 im Abschnitt metadata.desktop zu finden, dass dort 

`-e "s#\@DISPLAY_NAME\@#${DISPLAY_NAME#g" \` 

fehlt und so  entsprechendes aus VERSION nicht generiert wird.

VERSION:

``` bash
[...]
WALLPAPER=patience
CODENAME_SAFE=patience
DISPLAY_NAME=Patience
VERSION=2015.1.0
DISTRIBUTION=unstable.
[...]
```

Wie gesagt es betrifft alle Themes, whiteroom, thunderstruck, patience usw.

``` text
apt policy sddm-theme-paintitblack sddm-theme-patience sddm-theme-thunderstruck sddm-theme-whiteroom

sddm-theme-paintitblack:
  Installiert:           2016.08.31-2

sddm-theme-patience:
  Installiert:           2016.1.0~alpha-6

sddm-theme-thunderstruck:
  Installiert:           2016.08.31-2

sddm-theme-whiteroom:
  Installiert:           2016.08.31-2
```

Ich würde es Dir ja in entsprechende Datei rein malen, aber ich finde mich gerade im Dschungel der branchen und Dateien nicht zurecht, mir fehlt der Faden der Ariadne, und wer weiß schon was einen da drinnen erwartet.

**Comment by hhl** [comment]
Ups sehe gerade das Du dies schon gemacht hast 4121096  , aber warum zur `<zensiert>` wird eine unvollständige Metadata.desktop ausgeliefert?

Und ja, ich habe alles gelöscht (purge) und wieder neu installiert.

**Comment by agaida** [comment]
Weil Du nicht gelesen hast, was ich geschrieben hab:

> should fix issue #5 with the next bootstrap
> es ist gefixt, es muss nur das Paket neu gestrapped und gebaut werden. Änderungen im Quelltext haben nich nie auf magische Art und Weise ein Problem in bereits erstellten Paketen beseitigt.
